version: '3.0'

networks:
  bot:
    driver: bridge

volumes:
  user-data:
    driver: local

services:
  bot:
    build:
      dockerfile: Dockerfile
    networks:
      bot:
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      HOST: ${HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME}

  db:
    image: 'postgres:16-alpine'
    networks:
      bot:
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - user-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}